version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ecomfest
      POSTGRES_PASSWORD: ecomfest
      POSTGRES_DB: ecomfest
    ports: ["5432:5432"]
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]
    volumes: ["minio-data:/data"]
volumes:
  minio-data:
